name: Update brew formula manually


on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Iter8 repo tag'
        required: true
      revision:
        description: 'Git commit id'
        required: true

jobs:
  update-brew:
    name: Update brew formula
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        VERSION=${{ github.event.inputs.ref }}
        REVISION=${{ github.event.inputs.revision }}
        envsubst < iter8.rb.tpl > iter8.rb
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply changes to brew formula        
