name: Update brew formula

on:
  repository_dispatch:
    types: [release]

jobs:
  update-brew:
    name: Update brew formula
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        export VERSION=${{ github.event.client_payload.ref }}
        export REVISION=${{ github.event.client_payload.sha }}
        envsubst < iter8.rb.tpl > iter8.rb
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply changes to brew formula
  test-brew-on-macos-11:
    name: Test brew formula on macos-11
    runs-on: macos-11
    needs: update-brew
    steps:
    - run: |
        brew unlink go@1.15
        brew tap iter8-tools/iter8
        brew install iter8
        brew test iter8
  test-brew-on-macos-10.5:
    name: Test brew formula on macos-10.5
    runs-on: macos-10.5
    needs: update-brew
    steps:
    - run: |
        brew unlink go@1.15
        brew tap iter8-tools/iter8
        brew install iter8
        brew test iter8        