name: Update brew formula manually


on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Iter8 tag'
        required: true

jobs:
  update-brew:
    name: Update brew formula
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        VERSION=${{ github.event.inputs.ref }}
        cat >iter8.rb <<EOF
        class Iter8 < Formula
          desc "Kubernetes release engineering"
          homepage "https://iter8.tools"
          url "https://github.com/iter8-tools/iter8.git",
              tag:      "${VERSION}",
          license "Apache-2.0"
          head "https://github.com/iter8-tools/iter8.git", branch: "master"

          depends_on "go" => :build

          def install
            # Don't dirty the git tree
            rm_rf ".brew_home"

            system "make", "build"
            bin.install "bin/iter8"
          end

          test do
            system bin/"iter8", "hub", "-e", "load-test"
            assert File.directory? testpath/"load-test/templates"

            version_output = shell_output(bin/"iter8 version 2>&1")
            assert_match "GitTreeState:\"clean\"", version_output
            if build.stable?
              assert_match "Version:\"v#{version}\"", version_output
            end
          end
        end
        EOF
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply changes to brew formula        
