name: Update brew formula

on:
  repository_dispatch:
    types: [release]

jobs:
  update-brew:
    name: Update brew formula
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        export VERSION=${{ github.event.client_payload.ref }}
        export REVISION=${{ github.event.client_payload.sha }}
        export SHA=${{ github.event.client_payload.shaformac }}
        envsubst < iter8.rb.tpl > iter8.rb
        export SEMVER=${VERSION//v}
        export MAJORMINOR=${SEMVER%.*}
        export SUFFIX=AT${MAJORMINOR//.}
        envsubst < iter8.rb.tpl > iter8@${MAJORMINOR}.rb
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply changes to brew formula
  test-brew-on-macos-11:
    name: Test brew formula on macos-11
    runs-on: macos-11
    needs: update-brew
    steps:
    - run: |
        brew tap iter8-tools/iter8
        brew install iter8
        brew test iter8
        brew uninstall iter8
        brew untap iter8-tools/iter8
    - run: |
        brew tap iter8-tools/iter8
        export VERSION=${{ github.event.client_payload.ref }}
        export SEMVER=${VERSION//v}
        export MAJORMINOR=${SEMVER%.*}
        brew install iter8@${MAJORMINOR}
        brew test iter8@${MAJORMINOR}
        brew uninstall iter8@${MAJORMINOR}
        brew untap iter8-tools/iter8
